-- CREATE DATABASE
CREATE DATABASE IOWEATHER;
USE IOWEATHER;

-- CREATE TABLES
-- Table: CHUVARADIA
CREATE TABLE CHUVARADIA (
    IDCHRAD int  NOT NULL,
    CHUVA decimal(5,1)  NOT NULL,
    RADIACAOGL decimal(10,1)  NOT NULL,
    CONSTRAINT PK_CHUVARADIA_IDCHRAD PRIMARY KEY (IDCHRAD)
);

-- Table: DATAHORA
CREATE TABLE DATAHORA (
    IDDTHR int  NOT NULL,
    DATA date  NOT NULL,
    HORA time  NOT NULL,
    CONSTRAINT PK_DATAHORA_IDDTHR PRIMARY KEY (IDDTHR)
);

-- Table: ESTACAO
CREATE TABLE ESTACAO (
    IDESTACAO varchar(10)  NOT NULL,
    NOMEESTACAO varchar(50)  NOT NULL,
    LATITUDE decimal(11,8)  NOT NULL,
    LONGITUDE decimal(11,8)  NOT NULL,
    ALTITUDE decimal(10,2)  NOT NULL,
    IDESTADOESTACAO int  NOT NULL,
    DATAFUNDACAO date  NOT NULL,
    CONSTRAINT PK_ESTACAO_IDESTACAO PRIMARY KEY (IDESTACAO)
);

-- Table: ESTADO
CREATE TABLE ESTADO (
    IDESTADO int  NOT NULL,
    NOMEESTADO varchar(50)  NOT NULL,
    SIGLAESTADO varchar(2)  NOT NULL,
    IDREGIAOESTADO int  NOT NULL,
    CONSTRAINT PK_ESTADO_IDESTADO PRIMARY KEY (IDESTADO)
);

-- Table: PRESSAOATM
CREATE TABLE PRESSAOATM (
    IDPRESSATM int  NOT NULL,
    PRESSAOATMESTACAO decimal(5,1)  NOT NULL,
    PRESSAOATMMAX decimal(5,1)  NOT NULL,
    PRESSAOATMMIN decimal(5,1)  NOT NULL,
    CONSTRAINT PK_PRESSAOATM_IDPRESSAOATM PRIMARY KEY (IDPRESSATM)
);

-- Table: REGIAO
CREATE TABLE REGIAO (
    IDREGIAO int  NOT NULL,
    NOMEREGIAO varchar(50)  NOT NULL,
    SIGLAREGIAO varchar(2)  NOT NULL,
    CONSTRAINT _K_REGIAO_IDREGIAO PRIMARY KEY (IDREGIAO)
);

-- Table: REGISTRO
CREATE TABLE REGISTRO (
    IDREGISTRO int  NOT NULL,
    IDREGESTACAO varchar(10)  NOT NULL,
    IDREGDTHR int  NOT NULL,
    IDREGCHUVA int  NOT NULL,
    IDREGTEMPAR int  NOT NULL,
    IDREGTEMPORV int  NOT NULL,
    IDREGPRESATM int  NOT NULL,
    IDREGVENTO int  NOT NULL,
    IDREGUMIDADE int  NOT NULL,
    CONSTRAINT PK_REGISTRO_IDREGISTRO PRIMARY KEY (IDREGISTRO)
);

-- Table: TEMPAR
CREATE TABLE TEMPAR (
    IDTEMPAR int  NOT NULL,
    TEMPARBULBOSECO decimal(5,1)  NOT NULL,
    TEMPARMAX decimal(5,1)  NOT NULL,
    TEMPARMIN decimal(5,1)  NOT NULL,
    CONSTRAINT PK_TEMPAR_IDTEMPAR PRIMARY KEY (IDTEMPAR)
);

-- Table: TEMPORVALHO
CREATE TABLE TEMPORVALHO (
    IDTEMPORV int  NOT NULL,
    TEMPORVPONTO decimal(5,1)  NOT NULL,
    TEMPORVALHOMAX decimal(5,1)  NOT NULL,
    TEMPORVALHOMIN decimal(5,1)  NOT NULL,
    CONSTRAINT PK_TEMPORVALHO_IDTEMPORV PRIMARY KEY (IDTEMPORV)
);

-- Table: UMIDADE
CREATE TABLE UMIDADE (
    IDUMIDADE int  NOT NULL,
    UMIDARELAR int  NOT NULL,
    UMIDADEMAX int  NOT NULL,
    UMIDADEMIN int  NOT NULL,
    CONSTRAINT PK_UMIDADE_IDUMIDADE PRIMARY KEY (IDUMIDADE)
);

-- Table: VENTO
CREATE TABLE VENTO (
    IDVENTO int  NOT NULL,
    VENTODIRECAOGRHR int  NOT NULL,
    VENTORAJMAX decimal(5,1)  NOT NULL,
    VENTOVELOHR decimal(5,1)  NOT NULL,
    CONSTRAINT PK_VENTO_IDVENTO PRIMARY KEY (IDVENTO)
);

-- FOREIGN KEYS
-- Reference: ESTACAO_ESTADO (table: ESTACAO)
ALTER TABLE ESTACAO ADD CONSTRAINT ESTACAO_ESTADO
    FOREIGN KEY (IDESTADOESTACAO)
    REFERENCES ESTADO (IDESTADO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ESTADO_REGIAO (table: ESTADO)
ALTER TABLE ESTADO ADD CONSTRAINT ESTADO_REGIAO
    FOREIGN KEY (IDREGIAOESTADO)
    REFERENCES REGIAO (IDREGIAO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_CHUVARADIA (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_CHUVARADIA
    FOREIGN KEY (IDREGCHUVA)
    REFERENCES CHUVARADIA (IDCHRAD)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_DATAHORA (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_DATAHORA
    FOREIGN KEY (IDREGDTHR)
    REFERENCES DATAHORA (IDDTHR)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_ESTACAO (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_ESTACAO
    FOREIGN KEY (IDREGESTACAO)
    REFERENCES ESTACAO (IDESTACAO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_PRESSAOATM (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_PRESSAOATM
    FOREIGN KEY (IDREGPRESATM)
    REFERENCES PRESSAOATM (IDPRESSATM)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_TEMPAR (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_TEMPAR
    FOREIGN KEY (IDREGTEMPAR)
    REFERENCES TEMPAR (IDTEMPAR)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_TEMPORVALHO (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_TEMPORVALHO
    FOREIGN KEY (IDREGTEMPORV)
    REFERENCES TEMPORVALHO (IDTEMPORV)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_UMIDADE (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_UMIDADE
    FOREIGN KEY (IDREGUMIDADE)
    REFERENCES UMIDADE (IDUMIDADE)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_VENTO (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_VENTO
    FOREIGN KEY (IDREGVENTO)
    REFERENCES VENTO (IDVENTO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- SEQUENCES
-- Sequence: CHUVARADIA_seq
CREATE SEQUENCE CHUVARADIA_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: DATAHORA_seq
CREATE SEQUENCE DATAHORA_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: ESTADO_seq
CREATE SEQUENCE ESTADO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: PRESSAOATM_seq
CREATE SEQUENCE PRESSAOATM_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: REGIAO_seq
CREATE SEQUENCE REGIAO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: REGISTRO_seq
CREATE SEQUENCE REGISTRO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: TEMPAR_seq
CREATE SEQUENCE TEMPAR_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: TEMPORVALHO_seq
CREATE SEQUENCE TEMPORVALHO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: UMIDADE_seq
CREATE SEQUENCE UMIDADE_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- Sequence: VENTO_seq
CREATE SEQUENCE VENTO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;

-- End of file.

