-- CREATE DATABASE
CREATE DATABASE ioweather
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Portuguese_Brazil.1252'
    LC_CTYPE = 'Portuguese_Brazil.1252'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

-- CREATE TABLES
-- Table: CHUVARADIA
CREATE TABLE CHUVARADIA (
    IDCHRAD int  NOT NULL,
    CHUVA decimal(5,1)  NOT NULL,
    RADIACAOGL decimal(10,1)  NOT NULL,
    CONSTRAINT PK_CHUVARADIA_IDCHRAD PRIMARY KEY (IDCHRAD)
);

-- Table: DATAHORA
CREATE TABLE DATAHORA (
    IDDTHR int  NOT NULL,
    DATA date  NOT NULL,
    HORA time  NOT NULL,
    CONSTRAINT PK_DATAHORA_IDDTHR PRIMARY KEY (IDDTHR)
);

-- Table: ESTACAO
CREATE TABLE ESTACAO (
	IDESTACAO int NOT NULL,
    ESTACAOWMO varchar(10)  NOT NULL,
    NOMEESTACAO varchar(50)  NOT NULL,
    LATITUDE decimal(11,8)  NOT NULL,
    LONGITUDE decimal(11,8)  NOT NULL,
    ALTITUDE decimal(10,2)  NOT NULL,
    IDESTADOESTACAO int  NOT NULL,
    DATAFUNDACAO date  NOT NULL,
    CONSTRAINT PK_ESTACAO_ESTACAOWMO PRIMARY KEY (ESTACAOWMO)
);

-- Table: ESTADO
CREATE TABLE ESTADO (
    IDESTADO int  NOT NULL,
    NOMEESTADO varchar(50)  NOT NULL,
    SIGLAESTADO varchar(2)  NOT NULL,
    IDREGIAOESTADO int  NOT NULL,
    CONSTRAINT PK_ESTADO_IDESTADO PRIMARY KEY (IDESTADO)
);

-- Table: PRESSAOATM
CREATE TABLE PRESSAOATM (
    IDPRESSATM int  NOT NULL,
    PRESSAOATMESTACAO decimal(5,1)  NOT NULL,
    PRESSAOATMMAX decimal(5,1)  NOT NULL,
    PRESSAOATMMIN decimal(5,1)  NOT NULL,
    CONSTRAINT PK_PRESSAOATM_IDPRESSAOATM PRIMARY KEY (IDPRESSATM)
);

-- Table: REGIAO
CREATE TABLE REGIAO (
    IDREGIAO int  NOT NULL,
    NOMEREGIAO varchar(50)  NOT NULL,
    SIGLAREGIAO varchar(2)  NOT NULL,
    CONSTRAINT _K_REGIAO_IDREGIAO PRIMARY KEY (IDREGIAO)
);

-- Table: REGISTRO
CREATE TABLE REGISTRO (
    IDREGISTRO int  NOT NULL,
    IDREGESTACAO varchar(10)  NOT NULL,
    IDREGDTHR int  NOT NULL,
    IDREGCHUVA int  NOT NULL,
    IDREGTEMPAR int  NOT NULL,
    IDREGTEMPORV int  NOT NULL,
    IDREGPRESATM int  NOT NULL,
    IDREGVENTO int  NOT NULL,
    IDREGUMIDADE int  NOT NULL,
    CONSTRAINT PK_REGISTRO_IDREGISTRO PRIMARY KEY (IDREGISTRO)
);

-- Table: TEMPAR
CREATE TABLE TEMPAR (
    IDTEMPAR int  NOT NULL,
    TEMPARBULBOSECO decimal(5,1)  NOT NULL,
    TEMPARMAX decimal(5,1)  NOT NULL,
    TEMPARMIN decimal(5,1)  NOT NULL,
    CONSTRAINT PK_TEMPAR_IDTEMPAR PRIMARY KEY (IDTEMPAR)
);

-- Table: TEMPORVALHO
CREATE TABLE TEMPORVALHO (
    IDTEMPORV int  NOT NULL,
    TEMPORVPONTO decimal(5,1)  NOT NULL,
    TEMPORVALHOMAX decimal(5,1)  NOT NULL,
    TEMPORVALHOMIN decimal(5,1)  NOT NULL,
    CONSTRAINT PK_TEMPORVALHO_IDTEMPORV PRIMARY KEY (IDTEMPORV)
);

-- Table: UMIDADE
CREATE TABLE UMIDADE (
    IDUMIDADE int  NOT NULL,
    UMIDARELAR int  NOT NULL,
    UMIDADEMAX int  NOT NULL,
    UMIDADEMIN int  NOT NULL,
    CONSTRAINT PK_UMIDADE_IDUMIDADE PRIMARY KEY (IDUMIDADE)
);

-- Table: VENTO
CREATE TABLE VENTO (
    IDVENTO int  NOT NULL,
    VENTODIRECAOGRHR int  NOT NULL,
    VENTORAJMAX decimal(5,1)  NOT NULL,
    VENTOVELOHR decimal(5,1)  NOT NULL,
    CONSTRAINT PK_VENTO_IDVENTO PRIMARY KEY (IDVENTO)
);

-- FOREIGN KEYS
-- Reference: ESTACAO_ESTADO (table: ESTACAO)
ALTER TABLE ESTACAO ADD CONSTRAINT ESTACAO_ESTADO
    FOREIGN KEY (IDESTADOESTACAO)
    REFERENCES ESTADO (IDESTADO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: ESTADO_REGIAO (table: ESTADO)
ALTER TABLE ESTADO ADD CONSTRAINT ESTADO_REGIAO
    FOREIGN KEY (IDREGIAOESTADO)
    REFERENCES REGIAO (IDREGIAO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_CHUVARADIA (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_CHUVARADIA
    FOREIGN KEY (IDREGCHUVA)
    REFERENCES CHUVARADIA (IDCHRAD)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_DATAHORA (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_DATAHORA
    FOREIGN KEY (IDREGDTHR)
    REFERENCES DATAHORA (IDDTHR)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_ESTACAO (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_ESTACAO
    FOREIGN KEY (IDREGESTACAO)
    REFERENCES ESTACAO (ESTACAOWMO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_PRESSAOATM (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_PRESSAOATM
    FOREIGN KEY (IDREGPRESATM)
    REFERENCES PRESSAOATM (IDPRESSATM)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_TEMPAR (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_TEMPAR
    FOREIGN KEY (IDREGTEMPAR)
    REFERENCES TEMPAR (IDTEMPAR)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_TEMPORVALHO (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_TEMPORVALHO
    FOREIGN KEY (IDREGTEMPORV)
    REFERENCES TEMPORVALHO (IDTEMPORV)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_UMIDADE (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_UMIDADE
    FOREIGN KEY (IDREGUMIDADE)
    REFERENCES UMIDADE (IDUMIDADE)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: REGISTRO_VENTO (table: REGISTRO)
ALTER TABLE REGISTRO ADD CONSTRAINT REGISTRO_VENTO
    FOREIGN KEY (IDREGVENTO)
    REFERENCES VENTO (IDVENTO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- SEQUENCES
-- Sequence: CHUVARADIA_IDCHRAD_seq
CREATE SEQUENCE CHUVARADIA_IDCHRAD_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE CHUVARADIA ALTER COLUMN IDCHRAD SET DEFAULT NEXTVAL('CHUVARADIA_IDCHRAD_seq'::regclass);

-- Sequence: DATAHORA_IDDTHR_seq
CREATE SEQUENCE DATAHORA_IDDTHR_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE DATAHORA ALTER COLUMN IDDTHR SET DEFAULT NEXTVAL('DATAHORA_IDDTHR_seq'::regclass);

-- Sequence: ESTACAO_IDESTACAO_seq
CREATE SEQUENCE ESTACAO_IDESTACAO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;	
ALTER TABLE ESTACAO ALTER COLUMN IDESTACAO SET DEFAULT NEXTVAL('ESTACAO_IDESTACAO_seq'::regclass);

-- Sequence: ESTADO_IDESTADO_seq
CREATE SEQUENCE ESTADO_IDESTADO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE ESTADO ALTER COLUMN IDESTADO SET DEFAULT NEXTVAL('ESTADO_IDESTADO_seq'::regclass);

-- Sequence: PRESSAOATM_IDPRESSATM_seq
CREATE SEQUENCE PRESSAOATM_IDPRESSATM_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE PRESSAOATM ALTER COLUMN IDPRESSATM SET DEFAULT NEXTVAL('PRESSAOATM_IDPRESSATM_seq'::regclass);

-- Sequence: REGIAO_IDREGIAO_seq
CREATE SEQUENCE REGIAO_IDREGIAO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE REGIAO ALTER COLUMN IDREGIAO SET DEFAULT NEXTVAL('REGIAO_IDREGIAO_seq'::regclass);

-- Sequence: REGISTRO_IDREGISTRO_seq
CREATE SEQUENCE REGISTRO_IDREGISTRO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE REGISTRO ALTER COLUMN IDREGISTRO SET DEFAULT NEXTVAL('REGISTRO_IDREGISTRO_seq'::regclass);

-- Sequence: TEMPAR_IDTEMPAR_seq
CREATE SEQUENCE TEMPAR_IDTEMPAR_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE TEMPAR ALTER COLUMN IDTEMPAR SET DEFAULT NEXTVAL('TEMPAR_IDTEMPAR_seq'::regclass);

-- Sequence: TEMPORVALHO_IDTEMPORV_seq
CREATE SEQUENCE TEMPORVALHO_IDTEMPORV_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE TEMPORVALHO ALTER COLUMN IDTEMPORV SET DEFAULT NEXTVAL('TEMPORVALHO_IDTEMPORV_seq'::regclass);

-- Sequence: UMIDADE_IDUMIDADE_seq
CREATE SEQUENCE UMIDADE_IDUMIDADE_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE UMIDADE ALTER COLUMN IDUMIDADE SET DEFAULT NEXTVAL('UMIDADE_IDUMIDADE_seq'::regclass);

-- Sequence: VENTO_IDVENTO_seq
CREATE SEQUENCE VENTO_IDVENTO_seq
      INCREMENT BY 1
      NO MINVALUE
      NO MAXVALUE
      START WITH 1
      NO CYCLE
;
ALTER TABLE VENTO ALTER COLUMN IDVENTO SET DEFAULT NEXTVAL('VENTO_IDVENTO_seq'::regclass);

-- INSERTS DATABASE INICIAL
INSERT INTO regiao (nomeregiao,siglaregiao)
VALUES 	('NORTE','N'),
		('NORDESTE','NE'),
		('NOROESTE','NO'),
		('CENTRO-OESTE','CO'),
		('LESTE','L'),
		('OESTE','O'),
		('SUL','S'),
		('SUDESTE','SU'),
		('SUDOESTE','SO');

INSERT INTO estado (nomeestado,siglaestado,idregiaoestado) 
VALUES	('Acre','AC',1),
		('Amapá','AP',1),
		('Amazonas','AM',1),
		('Pará','PA',1),
		('Rondônia','RO',1),
		('Roraima','RR',1),
		('Tocantins','TO',1),
		('Alagoas','AL',2),
		('Bahia','BA',2),
		('Ceará','CE',2),
		('Maranhão','MA',2),
		('Paraíba','PB',2),
		('Pernambuco','PE',2),
		('Piauí','PI',2),
		('Rio Grande do Norte','RN',2),
		('Sergipe','SE',2),
		('Distrito Federal','DF',4),
		('Goiás','GO',4),
		('Mato Grosso','MT',4),
		('Mato Grosso do Sul','MS',4),
		('Paraná','PR',7),
		('Rio Grande do sul','RS',7),
		('Santa Catarina','SC',7),
		('Espírito Santo','ES',8),
		('Minas Gerais','MG',8),
		('Rio de Janeiro','RJ',8),
		('São Paulo','SP',8);




-- End of file.

